#Before install
before_install
  - sudo apt install hugo python-pygments 
# Clean and don't fail
install:
  - rm -rf public || exit 0
# Build the website
script:
  - hugo -vv --theme=hugo-coder-portfolio
# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  keep_history: true
  on:
    branch: master
